engines:
  checkstyle:
    enabled: true
    channel: "beta"
    checks:
      com.puppycrawl.tools.checkstyle.checks.naming.PackageNameCheck:
        enabled: false

ratings:
  paths:
  - "**.java"
  
exclude_paths:
  - "src/test/"
